plotly/dash-ag-grid

- CHANGELOG.md
- src/lib/fragments/AgGrid.react.js
fixes #17
Added n_clicks data so `setProps` would update the data when the same cell is clicked on.
> add n_clicks to cellClicked 

- src/lib/renderers/markdownRenderer.js
Altering the `dangerously_allow*` component to be looking at `dangerously_allow_code` instead of `dangerously_allow_html`.
> Fixing Markdown Renderer

- src/lib/renderers/markdownRenderer.js
- tests/test_markdown_components.py
- addressing issue https://github.com/plotly/dash-ag-grid/issues/44
- added test in markdown component to not replace `targetLink` if `dangerously_allow_code` is true
- added tests for markdown
> Fixing Markdown replacing `linkTarget` in raw HTML:

- .circleci/config.yml
- .eslintrc
- package-lock.json
- package.json
- src/lib/fragments/AgGrid.react.js
- src/lib/renderers/rowMenuRenderer.js
- Upgrade to AG Grid 29.1, and switch `>=` to `^` so we don't accidentally get v30 whenever that's released
- Minor lint & build updates
- Add `eslint` linting to CI - but for now leaving `prettier` out of that, there will be lots of changes when we do that so I'll wait until there is less other work in progress.
> Dep updates 20230307

- CHANGELOG.md
- src/lib/components/AgGrid.react.js
- src/lib/fragments/AgGrid.react.js
- src/lib/utils/propCategories.js
- tests/test_dangerous_templates.py
- tests/test_filter.py
- tests/test_sizing_buttons.py
- info from the grid (#109)
- added output for `test_filter`
- added check for action props to delay until the grid is ready (#99)
- adjusted and fixed html templates (#116)
> adding support for `filterModel`

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/fragments/AgGrid.react.js
- src/lib/renderers/markdownRenderer.js
- src/lib/utils/propCategories.js
- tests/test_column_state.py
- tests/test_markdown_components.py
- tests/test_row_groupings.py
- tests/utils.py
`columnState` floats during grid interaction and only gets pushed when sent in a callback
`columnDefs` trumps `columnState` if it is pushed in a callback without a `columnState`
`Markdown` renderer now will pass back '' instead of `undefined` if there isnt a value
> floating-columnState

- CHANGELOG.md
- src/lib/fragments/AgGrid.react.js
- src/lib/utils/propCategories.js
- tests/test_column_state.py
* migrated props that use `setProps` from `render()` to `componentDidUpdate` (this fixed the `bad setState()` error)
* adjusted `columnState` if statement to use `prevProps.loading_state`
> fixing `columnState` for use with React 18

- .circleci/config.yml
- CHANGELOG.md
- src/lib/fragments/AgGrid.react.js
- tests/test_recursive_functions.py
where grid components werent passed down to detail grids
> Fixing issue #237

- CHANGELOG.md
- src/lib/fragments/AgGrid.react.js
- src/lib/utils/propCategories.js
- tests/assets/dashAgGridFunctions.js
- tests/requirements.txt
- tests/test_context_menu.py
- tests/test_custom_filter.py
- tests/test_is_row_master.py
- tests/test_popupparent.py
adding filter to be allowed as a functional component without params
> allowing more functions

- CHANGELOG.md
- package.json
- src/lib/components/AgGrid.react.js
- src/lib/fragments/AgGrid.react.js
- src/lib/utils/debounce.js
- tests/test_cell_value_changed.py
- tests/utils.py
Currently, the `cellValueChanged` events are propagated to Dash one-by-one. This becomes a problem in cases, where events are fires faster than Dash can handle them, e.g. when pasting multiple cells into the grid. For these cases, only the first event triggers a Dash callback, with all other changes lost. 
This PR changes the event collection mechanism to include all events fired within a specific time window (with the length currently defined by `CELL_VALUE_CHANGED_DEBOUNCE_MS = 1`). By making the window large enough that all events in e.g. a multi cell paste operation can be processed (initial tests indicate that 1 ms is sufficient), all changes can be propagted to Dash. Hence the callback will now receieve a _list_ of change events rather than a _single_ change event.
Here is a small …
> Propagate muti-cell paste event to Dash

- CHANGELOG.md
- src/lib/components/AgGrid.react.js
Allow for up to 2 minutes before `getApiAsync` fails.
> Update getApiAsync to allow for a longer timeout

- .circleci/config.yml
- package-lock.json
- package.json
- webpack.config.js
adjustments to webpack to improve build speed
> adjustments to webpack to improve build speed

- .github/workflows/release.yml
- CONTRIBUTING.md
- package.json
- requires-dev.txt
With this PR, when a new tag `v*` is pushed, a draft release will be created with the build files automatically attached.
Then, someone from the Plotly team should publish that draft release and upload the files to PyPI using Twine.
> Automate generation of build files

- CHANGELOG.md
- src/lib/fragments/AgGrid.react.js
- src/lib/utils/propCategories.js
- tests/test_scroll_to.py
Fixing issue with `scrollTo` not being reset after being used.
```
import dash_ag_grid as dag
from dash import Dash, html, dcc, Input, Output, State, callback
import pandas as pd
import dash_bootstrap_components as dbc
app = Dash(__name__, external_stylesheets=[dbc.themes.BOOTSTRAP])
df = pd.read_csv(
"https://raw.githubusercontent.com/plotly/datasets/master/ag-grid/olympic-winners.csv"
)
columnDefs = [
{"headerName": "Row", "valueGetter": {"function": "params.node.rowIndex", 'pinned': True}}
] + [{"field": c} for c in df.columns]
app.layout = dbc.Container(
[
dbc.Row(
[
dbc.Col(
[
dbc.Label("Row index"),
dbc.Input(
id="row-index-scroll-to",
type="number",
min=0,
max=df.shape[0] - 1,
step=1,
),
dbc.Label("Row Position"),
dcc.Dropdown(
options=["top", "bottom", "middle"], …
```
> Fix scroll to

- CHANGELOG.md
- src/lib/utils/propCategories.js
- tests/assets/dashAgGridFunctions.js
- tests/test_pivot_column_order.py
> Fix pivotComparator 

- CHANGELOG.md
- src/lib/fragments/AgGrid.react.js
- tests/test_cell_data_type_override.py
- tests/test_column_state.py
Fixes #299.
* testing for grid destroyed before trying to get the state
> fix for JSON Parse error when using dash_ag_grid and dash pages

- CHANGELOG.md
- src/lib/fragments/AgGrid.react.js
- tests/test_infinite_scroll.py
adjusting `handleDynamicStyle` to check if the `params.data` exists before running the test
closes #321
> adjusting `handleDynamicStyle`

- CHANGELOG.md
- src/lib/fragments/AgGrid.react.js
creating `customSetProps` to handle `setProps` when component no longer in dash tree
> creating `customSetProps` to handle `setProps`

- package.json
- requires-dev.txt
updating `dist` script to remove the build and dist directories before building
> dist script update

- .github/workflows/release.yml
- package-lock.json
- package.json
For some reason on `release.yml`, tests were being run before packages were installed.
> Run pytest after package installation

- .github/workflows/build.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/release.yml
- CONTRIBUTING.md
I've added the right secret to this repository so we should be good to go once this is merged, and can verify everything works at the next release.
> Automatically publish release to PyPi after publishing Github Release

- CHANGELOG.md
- src/lib/fragments/AgGrid.react.js
- tests/test_conditional_formatting.py
adjusting styling to check if the `node` exists, instead of testing for `data`, this fixes an issue with `rowGrouping` not passing through the styling conditions
> Fix Styling for Nodes

- CHANGELOG.md
- src/lib/components/AgGrid.react.js
- src/lib/fragments/AgGrid.react.js
- src/lib/utils/propCategories.js
- tests/assets/dashAgGridFunctions.js
- tests/test_event_listeners.py
this adds the ability for devs to define custom event data without needing to retrofit another prop
> Adding EventData Prop

- .github/workflows/publish-to-pypi.yml
- .github/workflows/release.yml
Separates into the `job` syntax rather than `steps`
> Seperate reusable workflow into named job

- .github/workflows/build.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/release.yml
We need to manually upload and download the artifacts from build to release/publish steps.
> Share artifacts between jobs

- .github/workflows/build.yml
- .github/workflows/publish-to-pypi.yml
- .github/workflows/release.yml
Split publishing of Python and NPM packages.
> Manage NPM packages properly

- .github/workflows/publish-to-pypi.yml
- .github/workflows/publish.yml
Properly fetch file name and pass to publish command.
> Fix NPM publish step

- .github/workflows/publish.yml
I have configured https://docs.pypi.org/trusted-publishers/adding-a-publisher/ in PyPI which means we no longer need API keys here.
> Use Trusted Publisher rather than API keys

- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docs/README.md
- more_examples/README.md
- more_examples/convert_units/app.py
- more_examples/demo_stock_portfolio_dmc/app.py
- more_examples/figure_with_tooltip/app.py
- requires-docs.txt
1. Minor typography fixes in `CHANGELOG.md`, `CODE_OF_CONDUCT.md`, and `CONTRIBUTING.md`.
1. Switch from `app.run_server` to `app.run` in `more_examples/*/*.py`.
1. Update use of Dash Mantine Compnents in `more_examples/demo_stock_portfolio_dmc/app.py`.
Note: filters do not appear to work correctly in `more_examples/convert_units` but that could be operator error - guidance would be appreciated.
Q: some of the examples in `more_examples` needed extra packages (listed below). Where should these be recorded?
-   `dash-bootstrap-components`
-   `dash-iconify`
-   `dash-mantine-components`
-   `pandas`
-   `yfinance`
> fix: bring `more_examples` up to date and minor formatting fixes in docs

- CHANGELOG.md
- package-lock.json
- src/lib/components/AgGrid.react.js
- src/lib/fragments/AgGrid.react.js
- src/lib/fragments/AgGridEnterprise.react.js
- src/lib/utils/propCategories.js
- tests/test_cell_data_type_override.py
- tests/test_column_state.py
- tests/test_event_listeners.py
- tests/test_pagination.py
- tests/test_scroll_to.py
- tests/test_sizing_buttons.py
This PR is a pure refactor from class to function components.
There is no functionality change. All automated tests continue to pass, and all example apps in `docs/` have been manually confirmed as working.
> Refactor: Migrate to function components

- tests/conftest.py
- tests/test_cell_data_type_override.py
This PR fixes the cell formatting test which can fail if the browser's locale is not `en-US`.
> Enforce a locale for cell formatting test

- src/lib/fragments/AgGrid.react.js
This PR fixes a flaky test (and real world problem) where pagination might not be set as per the prop, depending on the order of operations in the component.
> Bugfix: race condition in paginationGoto prop

- package-lock.json
- src/lib/fragments/AgGrid.react.js
- src/lib/utils/propCategories.js
- tests/examples/single_row_selection_remove_checkboxes.py
Hi guys! A tiny PR to:
- add `rowSelection` in GRID_NESTED_FUNCTIONS, that allows nested functions for `checkboxes ` and `isRowSelectable` (already in GRID_MAYBE_FUNCTIONS)
- add `checkboxes ` in GRID_MAYBE_FUNCTIONS, now nested in `rowSelection`
- remove deprecated `checkboxSelection` and `headerCheckboxSelection`
- add an example using `checkboxes ` as function
> Add `checkboxes` and `rowSelection` to propCategories.js

- CHANGELOG.md
- package-lock.json
- package.json
- src/lib/components/AgGrid.react.js
- src/lib/fragments/AgGrid.react.js
- src/lib/fragments/AgGridEnterprise.react.js
- src/lib/utils/propCategories.js
- tests/conftest.py
- tests/examples/single_row_selection_remove_checkboxes.py
- tests/test_cell_data_type_override.py
- tests/test_column_state.py
- tests/test_event_listeners.py
- tests/test_pagination.py
- tests/test_scroll_to.py
- tests/test_sizing_buttons.py
Main is currently at v32, should merge before bringing v33 into the main branch
> Merge Main into v32

- src/lib/components/AgGrid.react.js
- src/lib/fragments/AgGrid.react.js
- src/lib/utils/propCategories.js
- tests/test_column_state.py
This PR cherry picks v33 changes back to v32:
* [column state bugfix](https://github.com/plotly/dash-ag-grid/pull/400)
* [remove defaultProps](https://github.com/plotly/dash-ag-grid/pull/392)
* fixes test that seems to fail for unrelated reasons (magic number used in test was now incorrect) - would like feedback on this! 46603dd
> Backport column state fix

- CHANGELOG.md
- package-lock.json
- package.json
- tests/test_column_state.py
- tests/test_sizing_buttons.py
Syncs `v32.3.2` release with main
> Release 33.3.2rc2
