plotly/dash-ag-grid

docs/demo_stock_portfolio.py
docs/demo_stock_portfolio_simple.py

@BSd3v I couldn't figure out how to get this working with `value(Formatter|Getter)Function`. This makes these stock demos work again but perhaps you can help me figure it out without `dangerously_allow_html`?

allow html in stock demos

---

docs/examples/layout/cell_styling.py
docs/examples/layout/row_styling.py
docs/examples/layout/row_styling_conditional.py
docs/examples/layout/row_styling_highlights.py
docs/pages/layout/cell_styling.py
docs/pages/layout/row_styling.py
docs/utils/nav.py

updated cell style section
added row style section

updated docs app

---

src/lib/fragments/AgGrid.react.js

fix build error on enterprise proptypes

---

docs/examples/clientside_data/rowTransaction.py
docs/examples/clientside_data/rowTransaction_async.py
docs/examples/rows/row_height.py
docs/examples/rows/row_height_auto.py
docs/pages/clientside_data/overview.py
docs/pages/clientside_data/updating_data.py
docs/pages/rows/row_height.py
docs/utils/nav.py
docs/utils/other_components.py

added rowTransaction and rowHeight

---

src/lib/components/AgGrid.react.js
tests/test_virtual_row_data.py

- by adding `rowModelType` as default `'clientSide'`
- added test for sort, and filter to update `virtualRowData`

Fixing `virtualRowData` 

---

docs/examples/clientside_data/rowTransaction.py
docs/examples/enterprise/infinite_scroll.py
docs/examples/other_examples/crossfilter.py
docs/examples/other_examples/popup_from_cell_click.py
docs/examples/other_examples/selections.py
docs/pages/getting_started/intro.py

changed selectionChanged to selectedRows

docs updates after #39

---

src/lib/fragments/AgGrid.react.js
src/lib/utils/functionVars.js
tests/assets/dashAgGridFunctions.js
tests/test_class_rules.py
tests/test_conditional_formatting.py
tests/utils.py

- added support for `cellClassRules`, `rowClassRules` and `getRowClass`
- added tests to check for each class rule under `test_class_rules.py`
- adjusted test for conditional formatting to include row conditional formatting

Cell and row styling including class rules

---

docs/examples/import_export/clipboard.py
docs/examples/import_export/clipboard_colstate.py
docs/pages/import_export/clipboard.py
docs/pages/import_export/export_data_as_csv.py
docs/pages/layout/row_styling.py

updated Import Export section
added dcc.Clipboard examples

updated docs

---

docs/assets/columns.css
docs/assets/dashAgGridComponentFunctions.js
docs/assets/dashAgGridFunctions.js
docs/examples/components/assets/dashAgGridComponentFunctions.js
docs/examples/components/markdown.py
docs/examples/components/markdown_html.py
docs/examples/components/markdown_link_targets.py
docs/examples/components/tooltip.py
docs/examples/rows/assets/dashAgGridFunctions.js
docs/examples/rows/assets/gridcss.css
docs/examples/rows/row_spanning.py
docs/pages/getting_started/intro.py
docs/pages/rows/row_sorting.py
docs/pages/rows/row_spanning.py
docs/utils/nav.py

bumped version number to a2
added row spanning example

Update docs for a3

---

CHANGELOG.md
src/lib/components/AgGrid.react.js
src/lib/fragments/AgGrid.react.js
src/lib/renderers/rowMenuRenderer.js
tests/assets/dashAgGridComponentFunctions.js
tests/test_custom_components.py
tests/test_row_menu.py

- Changing `clickData` to `cellRendererData` to more closely line up with what this does

Click data cell renderer data

---

CHANGELOG.md
src/lib/renderers/customFunctions.js

- adding logging function available by default, available via `{"function": "log()"}`

Adding logging function

---

.circleci/config.yml
src/demo/App.js
src/lib/LazyLoader.js
src/lib/components/AgGrid.react.js
src/lib/fragments/AgGrid.react.js
src/lib/fragments/AgGridEnterprise.react.js
src/lib/renderers/customFunctions.js
src/lib/renderers/markdownRenderer.js
src/lib/renderers/rowMenuRenderer.js
src/lib/utils/functionVars.js

@BSd3v @AnnMarieW After this PR, `prettier` will be enforced by CI, so before committing any code change you should run:
```
npm run format
```
which will run both `eslint --fix` and `prettier --write`. Usually this will automatically fix any issues, but occasionally it'll fail and tell you to fix something manually.

run prettier

---

package-lock.json
package.json

minor updates only - mainly motivated by the webpack vulnerability reported today as fixed by 5.76

dep updates

---

CHANGELOG.md
src/lib/fragments/AgGrid.react.js
tests/test_default_styles.py

- added test for `defaultStyle` in the `cellStyle` when `styleConditions` is not also provided
- added tests for `defaultStyle`

Fixing `defaultStyle` in the `cellStyle` prop when only listed

---

README.md
docs/utils/nav.py

a4 - update for v4

---

src/lib/components/AgGrid.react.js

updated docstring for suppressDragLeaveHidesColumns

---

package-lock.json
package.json

Dep updates and version bump rc2

---

package-lock.json
package.json
src/lib/fragments/AgGrid.react.js

Removed `d3-array` from the custom functions API - we haven't found any clear use cases for this and it's pretty big (~70k in the minified bundle).
I included a couple of minor dep bumps as well, and set the version to 2.0.0!!!

No d3 array

---

docs/examples/persistence/persistence_selected_rows.py
docs/pages/persistence/persistence.py
docs/utils/nav.py
src/lib/components/AgGrid.react.js

Docs 2.0.0

---

docs/assets/columns.css
docs/examples/columns/assets/columns.css
docs/examples/columns/column_headers1.py
docs/examples/columns/column_moving.py
docs/examples/columns/column_pinning1.py
docs/examples/columns/column_pinning2.py
docs/examples/columns/column_sizing2.py
docs/examples/columns/column_state.py
docs/pages/columns/column_headers.py
docs/pages/columns/column_moving.py
docs/pages/columns/column_pinning.py
docs/pages/columns/column_sizing.py

Hello !
Next batch of docs review 📝
Today, pages:
- Column sizing
- Column moving
- Column pinning
\+ Minor modifications of pages Column headers and Column state

Docs review - batch 2

---

docs/assets/columns.css
docs/examples/columns/assets/columns.css

Fix example in Column Headers: Remove .css formatting of floating filters

---

docs/requirements.txt

updated requirements.txt for the docs

---

docs/assets/columns.css
docs/assets/dashAgGridComponentFunctions.js
docs/assets/dashAgGridFunctions.js
docs/assets/rows.css
docs/examples/columns/assets/dashAgGridFunctions.js
docs/examples/columns/column_spanning1.py
docs/examples/rows/assets/dashAgGridComponentFunctions.js
docs/examples/rows/assets/dashAgGridFunctions.js
docs/examples/rows/assets/gridcss.css
docs/examples/rows/assets/rows.css
docs/examples/rows/row_dragging.py
docs/examples/rows/row_dragging_custom_dragger.py
docs/examples/rows/row_dragging_drag_text.py
docs/examples/rows/row_dragging_drag_text_multi_dragger.py
docs/examples/rows/row_dragging_entire_row.py
docs/examples/rows/row_height_getRowHeight.py
docs/examples/rows/row_sorting_post_sort.py
docs/examples/rows/row_spanning.py
docs/examples/rows/row_spanning_complex.py
docs/pages/columns/column_spanning.py
docs/pages/rows/row_dragging.py
docs/pages/rows/row_height.py
docs/pages/rows/row_pinning.py
docs/pages/rows/row_sorting.py
docs/pages/rows/row_spanning.py

Hello !
Next batch of docs review 📝
Today, pages:
- Row Spanning
- Row Pinning
- Row Height
- Row Dragging
\+ and minor modifs in Column Spanning and Row Sorting

Docs review - batch 4

---

package-lock.json
package.json

Minor dep updates. Two I skipped:
- AG Grid 30.0.1 - we'll want to test that more thoroughly
- react-docgen 6.0.0 - I'd like to investigate if we can take that out of our components entirely, and just have Dash bring its own, since that's where it's used.

dep updates 2023-06-16

---

.circleci/config.yml
CHANGELOG.md
src/lib/components/AgGrid.react.js
src/lib/index.js
tests/test_grid_apis.py

* allows for rendering to take place and to wait until it is available

allow `dash_ag_grid` api to be an async function

---

CHANGELOG.md
src/lib/fragments/AgGrid.react.js
tests/test_row_groupings.py

- also fixed `virtualRowData` to only include nodes where there is data

fixing row-grouping editing

---

docs/app.py
docs_redirects/app.py

redirect pythonanywhere docs closes

---

docs_redirects/app.py

Add redirects to new pages:
- crossfilter
- scrolling-performance
- virtual-row-data
Also for:
- select-everything-or-filtered
- selection-checkbox
- text-selection
Those redirects don't work yet as the PRs on the official docs are not merged, but soon... 🤞

Add redirects to new pages of the official docs

---

src/lib/fragments/AgGrid.react.js
tests/test_column_state.py
tests/test_selected_rows.py

Fix selected rows issues

---

CHANGELOG.md
package.json

Bump to 31.2.0

---

.github/workflows/release.yml

Adds a missing step to install Python reqs.

Install requirements before generating dist

---

.github/workflows/release.yml

Fix typo in venv activation

---

.github/workflows/python-test.yml
.github/workflows/release.yml

We've updated the workflow files with the more granular scoped permissions, please test and approve as needed.
cc @amaranthjinn

updated release.yml + python-test.yml to include more scoped permissions as per issue #337

---

CHANGELOG.md
package-lock.json
package.json

let's see if the gods are smiling

release: 31.3.1rc1

---

.github/workflows/release.yml

Sets correct permissions for actions

Set correct permissions

---

.github/workflows/build.yml

Replace with the new test step

Change test step for CI

---

CHANGELOG.md
package-lock.json
package.json

Bump to v32.3.0rc0

---

.github/workflows/publish.yml

I hope this resolves the issues publishing to NPM. See: https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages

Add setup-node step

---

.github/workflows/python-test.yml
CHANGELOG.md
package-lock.json
package.json

Syncs with the `v32` branch for next RC release.

`v33.3.2rc1`
